# Generated by Django 4.1.2 on 2022-10-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_model_mod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mod',
            new_name='Model',
        ),
    ]
