# Generated by Django 4.1.2 on 2022-10-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_order_color_alter_order_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(help_text='Hex color', max_length=15),
        ),
    ]
